name: Publish Tiki to Nuget.org

on:
  workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '10.x'

    - name: Install dependencies
      run: |
        dotnet restore src/TikiSdk.Core/TikiSdk.Core.csproj
        dotnet restore src/TikiSdk/TikiSdk.csproj

    - name: Build
      run: |
        dotnet build src/TikiSdk.Core/TikiSdk.Core.csproj --configuration Release --no-restore
        dotnet build src/TikiSdk/TikiSdk.csproj --configuration Release --no-restore

    - name: Publish to Nuget.org
      run: |
        rm -rf nuget/

        dotnet pack --no-build src/TikiSdk.Core/TikiSdk.Core.csproj --configuration Release --output nuget
        dotnet pack --no-build src/TikiSdk/TikiSdk.csproj --configuration Release --output nuget

        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json
